---
# Install python if missing.
- hosts: all
  gather_facts: False

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

# Playbook for GoRTC web server.
# Ubuntu 16.04 is expected.
- hosts: all
  roles:
    - gortc.go
    - geerlingguy.nginx
  vars:
    nginx_vhosts:
      - listen: "443 ssl http2"
        server_name: "gortc.io"
        state: "present"
        file: "web.conf"
        template: "{{ nginx_vhost_template }}"
        extra_parameters: |
          location / {
            proxy_pass http://localhost:3000;
          }
          ssl_certificate     /home/web/ssl/gortc.io.crt;
          ssl_certificate_key /home/web/ssl/gortc.io.key;
          ssl_protocols       TLSv1.1 TLSv1.2;
  tasks:
    - name: install web
      notify: restart web
      become: true
      become_user: web
      git:
        repo: https://github.com/cydev/web.git
        dest: /home/web/go/src/github.com/cydev/web
    - name: build
      become: true
      become_user: web
      make:
        chdir: /home/web/go/src/github.com/cydev/web
        target: build-prod
    - name: install systemd service file
      template: src=web.service.j2 dest=/etc/systemd/system/web.service
      notify: restart web
    - name: ensure that service is enabled and started
      systemd:
        name: web
        state: started
        enabled: yes
        daemon_reload: yes
  pre_tasks:
    - name: update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

    - name: install common packages
      apt: pkg={{ item }} state=present update_cache=yes
      with_items:
        - git
        - htop
        - unzip
        - python-pip

    - name: remove require tty
      lineinfile: regexp="^\s+\w+\s+requiretty" dest=/etc/sudoers state=absent
  handlers:
    - name: restart web
      service: name=web state=restarted